name: SYCL Profiler

on:
  schedule:
    - cron:  '00 00 * * *'

jobs:
  sycl_v100s_Profiling:
    name: SYCL V100S Profiling
    env:
      SYCL_NAME_PREFIX: sycl_Xeon-Silver-4216_v100s_gcc-11.3_cuda-11.6.2
      ENABLE_CI_PROFILER: 1

      MADGRAPH4GPU_DB_SECRET: ${{ secrets.MADGRAPH4GPU_DB_SECRET }}
    runs-on: [self-hosted, linux, v100s]
    steps:
    - uses: actions/checkout@v2
    - name: Runs SYCL performanceProfiler.py script
      run: cd tools/profiling/; source /cvmfs/sft.cern.ch/lcg/contrib/gcc/11.3.0/x86_64-centos8/setup.sh; python3 performanceProfiler.py -l 'SYCL' -b 'master'
    - name: Uploads SYCL JSON files to DB
      run: cd tools/profiling/; python3 sendData.py --profiler --absLayer "SYCL" --branch master